In [52]:
import pandas as pd
import os
import numpy as np
import torch

In [2]:
sd = pd.read_csv('sigData.csv',names=['Frame Number','Affordance Name','Ground Truth Affordance','Predicted Affordance','Confidence Score'])

In [3]:
sd.head()

Frame Number Affordance Name Ground Truth Affordance Predicted Affordance  \
0             1          Hazard                   False                False   
1             1         Traffic                       0                 True   
2             1       SpeedSign                      -1                   -1   
3             1         Vehicle                      50                   50   
4             1      CenterDist       0.367385968703215    0.348112989432316   

   Confidence Score  
0          0.980226  
1          0.596183  
2          0.987572  
3               NaN  
4               NaN

In [4]:
me = pd.read_csv('measurements.csv')

In [5]:
me.head()

pos_x       pos_y  intersection_otherlane    long_accel  \
0  71.040039  237.429993                     0.0 -3.758871e-12   
1  71.040039  237.429993                     0.0 -3.756992e-12   
2  71.040039  237.429993                     0.0 -3.755115e-12   
3  71.040039  237.429993                     0.0 -3.753234e-12   
4  71.040039  237.429993                     0.0 -3.751359e-12   

   intersection_offroad  collision_other  end_point  rep  direction  \
0                   0.0              0.0          8    0          0   
1                   0.0              0.0          8    0          0   
2                   0.0              0.0          8    0          0   
3                   0.0              0.0          8    0          0   
4                   0.0              0.0          8    0          0   

   gametimeStamp  weather  brake  steer  exp_id  throttle     lat_accel  \
0            100        8    0.0    0.0       0       0.8 -3.093982e-25   
1            150        8    0.0    0.0       0       0.8  1.965348e-24   
2            200        8    0.0    0.0       0       0.8  3.929902e-24   
3            250        8    0.0    0.0       0       0.8 -2.170556e-24   
4            300        8    0.0    0.0       0       0.8 -3.411327e-24   

   start_point  collision_pedestrians  collision_vehicles  centerDist  
0           34                    0.0                 0.0    0.367386  
1           34                    0.0                 0.0    0.367386  
2           34                    0.0                 0.0    0.367386  
3           34                    0.0                 0.0    0.367386  
4           34                    0.0                 0.0    0.367386

In [6]:
df = pd.DataFrame()

In [7]:
sd = sd.drop(['Predicted Affordance','Confidence Score'],axis=1)

In [8]:
df = sd.groupby(['Frame Number','Affordance Name']).first()

In [9]:
df = df.unstack(level =-1)

In [10]:
df.reset_index(inplace=True)

In [11]:
df.head()

Frame Number Ground Truth Affordance                        \
Affordance Name                           CenterDist Hazard Relative Angle   
0                          1       0.367385968703215  False   -3.141586262   
1                          2       0.367385968703215  False   -3.141586262   
2                          3       0.367385968703215  False   -3.141586262   
3                          4       0.367385968703215  False   -3.141586262   
4                          5       0.367385968703215  False   -3.141586262   

                                           
Affordance Name SpeedSign Traffic Vehicle  
0                      -1       0      50  
1                      -1       0      50  
2                      -1       0      50  
3                      -1       0      50  
4                      -1       0      50

In [12]:
dff = pd.DataFrame(df['Ground Truth Affordance'])

In [13]:
dff.columns.name = None

In [14]:
dff['direction'] = me['direction']

In [15]:
dff.head()

CenterDist Hazard Relative Angle SpeedSign Traffic Vehicle  \
0  0.367385968703215  False   -3.141586262        -1       0      50   
1  0.367385968703215  False   -3.141586262        -1       0      50   
2  0.367385968703215  False   -3.141586262        -1       0      50   
3  0.367385968703215  False   -3.141586262        -1       0      50   
4  0.367385968703215  False   -3.141586262        -1       0      50   

   direction  
0          0  
1          0  
2          0  
3          0  
4          0

In [16]:
dff.columns = ['center_distance','hazard_stop','relative_angle','speed_sign','red_light','veh_distance','direction']

In [17]:
red = [i=='2' for i in dff['red_light']]

In [18]:
dff['red_light']=red

In [19]:
path = '/home/vasu/Desktop/project/CameraRGB'
l=os.listdir(path)
li=[x for x in l]

In [20]:
li.sort()

In [21]:
dff['im_name']=li

In [22]:
dff.head()

center_distance hazard_stop relative_angle speed_sign  red_light  \
0  0.367385968703215       False   -3.141586262         -1      False   
1  0.367385968703215       False   -3.141586262         -1      False   
2  0.367385968703215       False   -3.141586262         -1      False   
3  0.367385968703215       False   -3.141586262         -1      False   
4  0.367385968703215       False   -3.141586262         -1      False   

  veh_distance  direction              im_name  
0           50          0  image_00000.jpg.png  
1           50          0  image_00001.jpg.png  
2           50          0  image_00002.jpg.png  
3           50          0  image_00003.jpg.png  
4           50          0  image_00004.jpg.png

In [23]:
p=0.1
n = int(len(dff)*(1-p))
m = len(dff)-n

In [24]:
valid = [False]*n + [True]*m

In [25]:
type(valid)

list

In [56]:
isvalid2 = (np.array(valid))

In [57]:
isvalid2.dtype

dtype('bool')

In [58]:
#isvalid2 = torch.from_numpy(isvalid2)

TypeError: can't convert np.ndarray of type numpy.bool_. The only supported types are: double, float, float16, int64, int32, and uint8.

In [59]:
isvalid2

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,

In [60]:
np.save('is_val.npy',isvalid2)

In [28]:
#np.array(valid).dump(open('is_val.npy','wb'))

In [29]:
dff['is_valid'] = valid

In [30]:
len(dff)

423

In [31]:
j=0
seq=[]
for i in range(len(dff)):
    if(i%10==0):
        j= j+1;
    seq.append(j)

In [32]:
dff['sequence'] = seq

In [33]:
dff.head()

center_distance hazard_stop relative_angle speed_sign  red_light  \
0  0.367385968703215       False   -3.141586262         -1      False   
1  0.367385968703215       False   -3.141586262         -1      False   
2  0.367385968703215       False   -3.141586262         -1      False   
3  0.367385968703215       False   -3.141586262         -1      False   
4  0.367385968703215       False   -3.141586262         -1      False   

  veh_distance  direction              im_name  is_valid  sequence  
0           50          0  image_00000.jpg.png     False         1  
1           50          0  image_00001.jpg.png     False         1  
2           50          0  image_00002.jpg.png     False         1  
3           50          0  image_00003.jpg.png     False         1  
4           50          0  image_00004.jpg.png     False         1

In [34]:
dff.tail()

center_distance hazard_stop  relative_angle speed_sign  red_light  \
418             0.9858       False  -1.66555878891         -1      False   
419  0.999397883727997       False  -1.66356780968         -1      False   
420             0.9858       False  -1.66215646746         -1      False   
421             0.9858       False  -1.66094193285         -1      False   
422  0.999397883727997       False  -1.65976068775         -1      False   

      veh_distance  direction              im_name  is_valid  sequence  
418  6.38390503775          1  image_00418.jpg.png      True        42  
419  6.44054482488          1  image_00419.jpg.png      True        42  
420  6.50791522533          1  image_00420.jpg.png      True        43  
421  6.58661385634          1  image_00421.jpg.png      True        43  
422  6.67688177787          1  image_00422.jpg.png      True        43

In [35]:
#export_csv = dff.to_csv (r'/home/vasu/Desktop/project/annotations.csv', index = None, header=True)

In [36]:
np.load(open('is_val.npy','rb'))

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,

In [37]:
x = np.array([1, 2, 4, 7, 0,6])

In [38]:
np.diff(x)

array([ 1,  2,  3, -7,  6])

In [39]:
np.where(np.diff(x))+np.array(1)

array([[1, 2, 3, 4, 5]])

In [40]:
np.array(1)

array(1)

In [41]:
np.squeeze(np.where(np.diff(x))+np.array(1))

array([1, 2, 3, 4, 5])

In [42]:
dff['seq_id'] = dff.index

In [43]:
dff.head()

center_distance hazard_stop relative_angle speed_sign  red_light  \
0  0.367385968703215       False   -3.141586262         -1      False   
1  0.367385968703215       False   -3.141586262         -1      False   
2  0.367385968703215       False   -3.141586262         -1      False   
3  0.367385968703215       False   -3.141586262         -1      False   
4  0.367385968703215       False   -3.141586262         -1      False   

  veh_distance  direction              im_name  is_valid  sequence  seq_id  
0           50          0  image_00000.jpg.png     False         1       0  
1           50          0  image_00001.jpg.png     False         1       1  
2           50          0  image_00002.jpg.png     False         1       2  
3           50          0  image_00003.jpg.png     False         1       3  
4           50          0  image_00004.jpg.png     False         1       4

In [44]:
export_csv = dff.to_csv (r'/home/vasu/Desktop/project/annotations.csv', index = None, header=True)